- name: "Hosts"
  hosts: all
  become: yes

  tasks:

   - name: "Docker-ce | apt-get update"
     apt: update_cache=yes

   - name: "Docker-ce | apt-get install"
     apt: name={{item}} state=present
     with_items:
     - apt-transport-https
     - ca-certificates
     - nfs-common
     - htop
     - cifs-utils
     - python-pip

   - name: "Docker-ce | key"
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present

   - name: "Docker-ce | add repository"
     apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
      update_cache: yes

   - name: "Docker-ce | apt-get update"
     apt: update_cache=yes

   - name: "Docker-ce | apt-get install docker-engine"
     apt: name={{item}} state=present
     with_items:
     - docker-ce

   - name: "Docker-ce | Install docker-compose"
     get_url:
      url: https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755
 
   - name: "Docker-ce | Adjustment permission docker-compose"
     file: path=/usr/local/bin/docker-compose mode=755
     ignore_errors: yes

   - name: "Docker-ce | Enable Docker init.d"
     service: name=docker enabled=yes
     ignore_errors: yes

   - name: "Docker-ce | Install Weave network"
     get_url:
      url: http://git.io/weave
      dest: /usr/local/bin/weave
     ignore_errors: yes

   - name: "Docker-ce | Adjustment permission weave"
     file: path=/usr/local/bin/weave mode=755
     ignore_errors: yes



